name: Keep Render Server Alive

on:
  schedule:
    - cron: "*/14 * * * *"   # alle 14 Minuten
  workflow_dispatch:         # manuelles Starten möglich

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: curl -I https://fcm-backend-nfes.onrender.com/
